### ISSUE TITLE
fix: Add contrast to terminal color with non-default settings

### ISSUE THREAD

**Issue by alexlokshin-czi** [chanzuckerberg/happy#217]
@danieljhegeman will provide additional details.

**Comment by danieljhegeman** [comment]
The current iteration of the `happy` client produces logs in black text. This is a problem for any engineer with a dark terminal background.

**Comment by jgadling** [comment]
I can confirm the same behavior in my terminal - I'm using iterm 3.4.15 with a dark background and the default `happy` output is using the color I have configured for "bright black" ... which is actually a dark gray and hard to read.

**Comment by edulop91** [comment]
Proposed initial fix: a `--no-color` and `HAPPY_NO_COLOR` that will disable colorizing in the CLI. 

We can then think of another solution
