### ISSUE TITLE
Check user authentication status and issue warning

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/happy#221]
If the user has not authenticated with TF Enterprise (recently), then `happy` commands file. E.g. `happy list` reports:
`failed to get workspace: could not read workspace <stack>: unauthorized`.  

The CLI could check the user's authentication status and explain that the user needs to (re)authenticate.

This behavior existed in the Happy CLI Python version.

**Comment by edulop91** [comment]
I think this should be fixed in newer versions of the CLI!
